
services:
  webserver:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "${BIND_IP:-0.0.0.0}:5678:5678"
    volumes:
      - ./nginx-conf/server.conf:/etc/nginx/conf.d/server.conf:ro
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs
    depends_on:
      - trilium
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:5678/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
      start-interval: 10s
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"


  trilium:
    hostname: trilium
    image: triliumnext/trilium:latest
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    expose:
      - 8080
    volumes:
      - /home/user/trilium-data:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

networks:
  default:
